### PR TITLE
Use dynamic libraries for plugins

### LINKED ISSUE #42: [FEATURE] Use dynamic libraries for plugins
**Is your feature request related to a problem? Please describe.**<br>
No, my issue is not related to a problem. However, it can be a potential measure against problems in future,

**Describe the solution you'd like**<br>
Currently, our Rust project uses binary plugins to extend its functionality. While this approach has worked well for us so far, it has some limitations. Binary plugins require users to download and install pre-compiled binaries that are specific to their system architecture and operating system. This can be difficult and error-prone, especially for users who are not familiar with compiling and installing software.

Another issue with binary plugins is that they can have performance implications. Binary plugins are statically linked to the application, which means they are loaded into memory at startup and cannot be unloaded until the application exits. This can lead to increased memory usage and slower startup times for the application. Dynamic libraries, on the other hand, are loaded and unloaded at runtime, which can help reduce memory usage and improve startup times.

In addition, binary plugins can pose security risks. Because they are compiled code, it can be difficult to verify their source and ensure they are not malicious. Dynamic libraries, on the other hand, can be loaded with stricter security measures, such as signed libraries, that help ensure the code is trusted and safe to use.

To address these issues, I propose that we switch to using dynamic libraries as plugins. Dynamic libraries can be loaded and unloaded at runtime, which means users can add and remove plugins without needing to download or compile any code. Dynamic libraries can also be updated more easily, since users can simply replace the library file.

**Additional context**<br>
To implement this, we would need to:

- Update our plugin system to support dynamic libraries. This would involve changing our plugin interface to use dynamic linking instead of static linking.

- Provide documentation and examples for users on how to create dynamic library plugins.

- Update our build process to include support for building dynamic library plugins.

I believe this change would make our project more user-friendly, easier to extend, and potentially more secure. Please let me know your thoughts on this proposal.

### PR DESCRIPTION
**Pull request by infinity-plus**
**What changes were made?**
Updated our plugin system to support dynamic libraries. This involves changing our plugin interface to use dynamic linking instead of static linking.

**This fixes an issue?**
Yes, Closes #42 

**Does this code introduce any issues or warnings?**
No

**Were you able to test on multiple platforms?**
If you were able to test it on multiple platforms, list them here

-   [x] Linux
-   [ ] Windows
-   [ ] macOS

### CODE REVIEW

**Review by Brisolo32 — CHANGES_REQUESTED** [review]
I'd only say that the files inside `private/` can be removed, since they won't be used anyway. They might be added again sometime, but for the meanwhile they're useless

**Comment by infinity-plus** [comment]
> I'd only say that the files inside `private/` can be removed, since they won't be used anyway. They might be added again sometime, but for the meanwhile they're useless
Can just be deleted without breaking anything?

**Comment by Brisolo32** [comment]
> 

Yes. For what I know, they aren't mentioned/imported anywhere

**Review by Brisolo32 — APPROVED** [review]
LGTM

**Comment by infinity-plus** [comment]
Merging.

**Pull request merged**
